### ISSUE TITLE
Como profe (y test automático) necesito que todo el código que se incorpore se haga por PR

### ISSUE THREAD

**Issue by JJ** [PalomitaTeam/FloWorking#9]
Y el test comprobará que hay al menos un test cerrado (que no es el caso)

**Comment by pablojjimenez** [comment]
¿Basta con introducir algún cambio mediante de un PR?

**Comment by JJ** [comment]
Bueno, para que pase el test sí, pero ya os digo que conviene que os acostumbréis a incorporar _todo_ mediante PRs, incluso cambios al README.md

**Comment by pablojjimenez** [comment]
#16

**Comment by pablojjimenez** [comment]
#16
